package send

import (
    "roproxy/internal/common"
)

var PacketDatabase = map[uint16]*common.PacketSpec{
    0x0436: {Desc: "Map Login", Size: 23, Type: common.FIXED, Handler: &MapLogin{}, Alert: false},
    // No implemented yet
    0x0064: {Desc: "Master Login", Size: 55, Type: common.FIXED, Handler: nil, Alert: false},
    0x0065: {Desc: "Game Login", Size: 17, Type: common.FIXED, Handler: nil, Alert: false},
    0x0066: {Desc: "Char Login", Size: 3, Type: common.FIXED, Handler: nil, Alert: false},
    0x0067: {Desc: "Char Create", Size: 37, Type: common.FIXED, Handler: nil, Alert: false},
    0x0068: {Desc: "Char Delete", Size: 46, Type: common.FIXED, Handler: nil, Alert: false},
    0x0072: {Desc: "Map Login", Size: 19, Type: common.FIXED, Handler: nil, Alert: false},
    0x007d: {Desc: "Map Loaded", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x007e: {Desc: "Sync", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0085: {Desc: "Character Move", Size: 5, Type: common.FIXED, Handler: nil, Alert: false},
    0x0089: {Desc: "Actor Action", Size: 7, Type: common.FIXED, Handler: nil, Alert: false},
    0x008c: {Desc: "Public Chat", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0090: {Desc: "Npc Talk", Size: 7, Type: common.FIXED, Handler: nil, Alert: false},
    0x0094: {Desc: "Actor Info Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0096: {Desc: "Private Message", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0099: {Desc: "Gm Broadcast", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x009b: {Desc: "Actor Look At", Size: 5, Type: common.FIXED, Handler: nil, Alert: false},
    0x009f: {Desc: "Item Take", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x00a2: {Desc: "Item Drop", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x00a7: {Desc: "Item Use", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x00a9: {Desc: "Send Equip", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x00ab: {Desc: "Send Unequip Item", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x00b2: {Desc: "Restart", Size: 3, Type: common.FIXED, Handler: nil, Alert: false},
    0x00b8: {Desc: "Npc Talk Response", Size: 7, Type: common.FIXED, Handler: nil, Alert: false},
    0x00b9: {Desc: "Npc Talk Continue", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x00bb: {Desc: "Send Add Status Point", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x00bf: {Desc: "Send Emotion", Size: 3, Type: common.FIXED, Handler: nil, Alert: false},
    0x00c1: {Desc: "Request User Count", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x00c5: {Desc: "Request Buy Sell List", Size: 7, Type: common.FIXED, Handler: nil, Alert: false},
    0x00c8: {Desc: "Buy Bulk", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x00c9: {Desc: "Sell Bulk", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x00cc: {Desc: "Gm Kick", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x00ce: {Desc: "Gm Kick All", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x00cf: {Desc: "Ignore Player", Size: 27, Type: common.FIXED, Handler: nil, Alert: false},
    0x00d0: {Desc: "Ignore All", Size: 3, Type: common.FIXED, Handler: nil, Alert: false},
    0x00d3: {Desc: "Get Ignore List", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x00d5: {Desc: "Chat Room Create", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x00d9: {Desc: "Chat Room Join", Size: 14, Type: common.FIXED, Handler: nil, Alert: false},
    0x00de: {Desc: "Chat Room Change", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x00e0: {Desc: "Chat Room Bestow", Size: 30, Type: common.FIXED, Handler: nil, Alert: false},
    0x00e2: {Desc: "Chat Room Kick", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x00e3: {Desc: "Chat Room Leave", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x00e4: {Desc: "Deal Initiate", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x00e6: {Desc: "Deal Reply", Size: 3, Type: common.FIXED, Handler: nil, Alert: false},
    0x00e8: {Desc: "Deal Item Add", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x00eb: {Desc: "Deal Finalize", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x00ed: {Desc: "Deal Cancel", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x00ef: {Desc: "Deal Trade", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x00f3: {Desc: "Storage Item Add", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x00f5: {Desc: "Storage Item Remove", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x00f7: {Desc: "Storage Close", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x00fc: {Desc: "Party Join Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x00ff: {Desc: "Party Join", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0100: {Desc: "Party Leave", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0102: {Desc: "Party Setting", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0103: {Desc: "Party Kick", Size: 30, Type: common.FIXED, Handler: nil, Alert: false},
    0x0108: {Desc: "Party Chat", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0112: {Desc: "Send Add Skill Point", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x0113: {Desc: "Skill Use", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0116: {Desc: "Skill Use Location", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x011b: {Desc: "Warp Select", Size: 20, Type: common.FIXED, Handler: nil, Alert: false},
    0x011d: {Desc: "Memo Request", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0126: {Desc: "Cart Add", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x0127: {Desc: "Cart Get", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x0128: {Desc: "Storage To Cart", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x0129: {Desc: "Cart To Storage", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x012a: {Desc: "Companion Release", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x012e: {Desc: "Shop Close", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0130: {Desc: "Send Entering Vending", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0134: {Desc: "Buy Bulk Vender", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x013f: {Desc: "Gm Item Mob Create", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x0140: {Desc: "Gm Move To Map", Size: 22, Type: common.FIXED, Handler: nil, Alert: false},
    0x0143: {Desc: "Npc Talk Number", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0146: {Desc: "Npc Talk Cancel", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0149: {Desc: "Alignment", Size: 9, Type: common.FIXED, Handler: nil, Alert: false},
    0x014d: {Desc: "Guild Check", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x014f: {Desc: "Guild Info Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0151: {Desc: "Guild Emblem Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0159: {Desc: "Guild Leave", Size: 54, Type: common.FIXED, Handler: nil, Alert: false},
    0x015b: {Desc: "Guild Kick", Size: 54, Type: common.FIXED, Handler: nil, Alert: false},
    0x015d: {Desc: "Guild Break", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0165: {Desc: "Guild Create", Size: 30, Type: common.FIXED, Handler: nil, Alert: false},
    0x0168: {Desc: "Guild Join Request", Size: 14, Type: common.FIXED, Handler: nil, Alert: false},
    0x016b: {Desc: "Guild Join", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x016e: {Desc: "Guild Notice", Size: 186, Type: common.FIXED, Handler: nil, Alert: false},
    0x0170: {Desc: "Guild Alliance Request", Size: 14, Type: common.FIXED, Handler: nil, Alert: false},
    0x0172: {Desc: "Guild Alliance Reply", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0178: {Desc: "Identify", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x017a: {Desc: "Card Merge Request", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x017c: {Desc: "Card Merge", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x017e: {Desc: "Guild Chat", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0187: {Desc: "Ban Check", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x018a: {Desc: "Quit Request", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x018e: {Desc: "Make Item Request", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0190: {Desc: "Skill Use Location Text", Size: 92, Type: common.FIXED, Handler: nil, Alert: false},
    0x0193: {Desc: "Actor Name Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0197: {Desc: "Gm Reset State Skill", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x0198: {Desc: "Gm Change Cell Type", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x019c: {Desc: "Gm Broadcast Local", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x019d: {Desc: "Gm Change Effect State", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x019f: {Desc: "Pet Capture", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x01a1: {Desc: "Pet Menu", Size: 3, Type: common.FIXED, Handler: nil, Alert: false},
    0x01a5: {Desc: "Pet Name", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x01a7: {Desc: "Pet Hatch", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x01a9: {Desc: "Pet Emotion", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x01ae: {Desc: "Make Arrow", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x01af: {Desc: "Change Cart", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x01b2: {Desc: "Shop Open", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x01ba: {Desc: "Gm Remove", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x01bb: {Desc: "Gm Shift", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x01bc: {Desc: "Gm Recall", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x01bd: {Desc: "Gm Summon Player", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x01c0: {Desc: "Request Remain Time", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x01ce: {Desc: "Auto Spell", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x01d5: {Desc: "Npc Talk Text", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x01db: {Desc: "Secure Login Key Request", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x01dd: {Desc: "Master Login", Size: 47, Type: common.FIXED, Handler: nil, Alert: false},
    0x01df: {Desc: "Gm Request Account Name", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x01e7: {Desc: "Novice Dori Dori", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x01ed: {Desc: "Novice Explosion Spirits", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x01f7: {Desc: "Adopt Reply Request", Size: 14, Type: common.FIXED, Handler: nil, Alert: false},
    0x01f9: {Desc: "Adopt Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x01fa: {Desc: "Master Login", Size: 48, Type: common.FIXED, Handler: nil, Alert: false},
    0x01fd: {Desc: "Repair Item", Size: 15, Type: common.FIXED, Handler: nil, Alert: false},
    0x0202: {Desc: "Friend Request", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0203: {Desc: "Friend Remove", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0204: {Desc: "Client Hash", Size: 18, Type: common.FIXED, Handler: nil, Alert: false},
    0x0208: {Desc: "Friend Response", Size: 14, Type: common.FIXED, Handler: nil, Alert: false},
    0x0212: {Desc: "Manner By Name", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x0213: {Desc: "Gm Request Status", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x0217: {Desc: "Rank Blacksmith", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0218: {Desc: "Rank Alchemist", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x021d: {Desc: "Less Effect", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0222: {Desc: "Refine Item", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0225: {Desc: "Rank Taekwon", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x022d: {Desc: "Homunculus Command", Size: 5, Type: common.FIXED, Handler: nil, Alert: false},
    0x0231: {Desc: "Homunculus Name", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x0232: {Desc: "Actor Move", Size: 9, Type: common.FIXED, Handler: nil, Alert: false},
    0x0233: {Desc: "Slave Attack", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x0234: {Desc: "Slave Move To Master", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0237: {Desc: "Rank Killer", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x023b: {Desc: "Storage Password", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x023f: {Desc: "Mailbox Open", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0241: {Desc: "Mail Read", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0243: {Desc: "Mail Delete", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0244: {Desc: "Mail Attachment Get", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0246: {Desc: "Mail Remove", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x0247: {Desc: "Mail Attachment Set", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x0248: {Desc: "Mail Send", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x024b: {Desc: "Auction Add Item Cancel", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x024c: {Desc: "Auction Add Item", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x024d: {Desc: "Auction Create", Size: 12, Type: common.FIXED, Handler: nil, Alert: false},
    0x024e: {Desc: "Auction Cancel", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x024f: {Desc: "Auction Buy", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0251: {Desc: "Auction Search", Size: 34, Type: common.FIXED, Handler: nil, Alert: false},
    0x0254: {Desc: "Starplace Agree", Size: 3, Type: common.FIXED, Handler: nil, Alert: false},
    0x025b: {Desc: "Cook Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x025c: {Desc: "Auction Info Self", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x025d: {Desc: "Auction Sell Stop", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0273: {Desc: "Mail Return", Size: 30, Type: common.FIXED, Handler: nil, Alert: false},
    0x0275: {Desc: "Game Login", Size: 37, Type: common.FIXED, Handler: nil, Alert: false},
    0x0288: {Desc: "Cash Dealer Buy", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0292: {Desc: "Auto Revive", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x029f: {Desc: "Mercenary Command", Size: 3, Type: common.FIXED, Handler: nil, Alert: false},
    0x02b0: {Desc: "Master Login", Size: 86, Type: common.FIXED, Handler: nil, Alert: false},
    0x02b6: {Desc: "Send Quest State", Size: 7, Type: common.FIXED, Handler: nil, Alert: false},
    0x02ba: {Desc: "Hotkey Change", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x02c4: {Desc: "Party Join Request By Name", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x02c7: {Desc: "Party Join Request By Name Reply", Size: 7, Type: common.FIXED, Handler: nil, Alert: false},
    0x02cf: {Desc: "Memorial Dungeon Command", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x02d6: {Desc: "View Player Equip Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x02d8: {Desc: "Misc Config Set", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x02db: {Desc: "Battleground Chat", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x02f1: {Desc: "Notify Progress Bar Complete", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x035f: {Desc: "Character Move", Size: 5, Type: common.FIXED, Handler: nil, Alert: false},
    0x0360: {Desc: "Sync", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0361: {Desc: "Actor Look At", Size: 5, Type: common.FIXED, Handler: nil, Alert: false},
    0x0362: {Desc: "Item Take", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0363: {Desc: "Item Drop", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0364: {Desc: "Storage Item Add", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x0365: {Desc: "Storage Item Remove", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x0366: {Desc: "Skill Use Location", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0367: {Desc: "Skill Use Location Text", Size: 92, Type: common.FIXED, Handler: nil, Alert: false},
    0x0368: {Desc: "Actor Info Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0369: {Desc: "Actor Name Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0437: {Desc: "Actor Action", Size: 7, Type: common.FIXED, Handler: nil, Alert: false},
    0x0438: {Desc: "Skill Use", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0439: {Desc: "Item Use", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x0443: {Desc: "Skill Select", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x0447: {Desc: "Blocking Play Cancel", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x044a: {Desc: "Client Version", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x07d7: {Desc: "Party Setting", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x07da: {Desc: "Party Leader", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x07e4: {Desc: "Item List Window Selected", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x07e7: {Desc: "Captcha Answer", Size: 32, Type: common.FIXED, Handler: nil, Alert: false},
    0x0801: {Desc: "Buy Bulk Vender", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0802: {Desc: "Booking Register", Size: 18, Type: common.FIXED, Handler: nil, Alert: false},
    0x0804: {Desc: "Booking Search", Size: 12, Type: common.FIXED, Handler: nil, Alert: false},
    0x0806: {Desc: "Booking Delete", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0808: {Desc: "Booking Update", Size: 14, Type: common.FIXED, Handler: nil, Alert: false},
    0x0811: {Desc: "Buy Bulk Openshop", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0815: {Desc: "Buy Bulk Closeshop", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0817: {Desc: "Buy Bulk Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0819: {Desc: "Buy Bulk Buyer", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0825: {Desc: "Token Login", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0827: {Desc: "Char Delete2", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0829: {Desc: "Char Delete2 Accept", Size: 12, Type: common.FIXED, Handler: nil, Alert: false},
    0x082b: {Desc: "Char Delete2 Cancel", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0835: {Desc: "Search Store Info", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0838: {Desc: "Search Store Request Next Page", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x083b: {Desc: "Search Store Close", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x083c: {Desc: "Search Store Select", Size: 12, Type: common.FIXED, Handler: nil, Alert: false},
    0x0841: {Desc: "Select Accessible Mapname", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x0842: {Desc: "Recall Sso", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0843: {Desc: "Remove Aid Sso", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0844: {Desc: "Cash Shop Open", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0846: {Desc: "Req Cash Tabcode", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x084a: {Desc: "Cash Shop Close", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x08b5: {Desc: "Pet Capture", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x08b8: {Desc: "Send Pin Password", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x08ba: {Desc: "New Pin Password", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x08be: {Desc: "Change Pin Password", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x08c1: {Desc: "Macro Start", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x08c2: {Desc: "Macro Stop", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x08c9: {Desc: "Request Cashitems", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x096e: {Desc: "Merge Item Request", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0970: {Desc: "Char Create", Size: 31, Type: common.FIXED, Handler: nil, Alert: false},
    0x0974: {Desc: "Merge Item Cancel", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x097c: {Desc: "Rank General", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x0987: {Desc: "Master Login", Size: 63, Type: common.FIXED, Handler: nil, Alert: false},
    0x098d: {Desc: "Clan Chat", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x098f: {Desc: "Char Delete2 Accept", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0998: {Desc: "Send Equip", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x09a1: {Desc: "Sync Received Characters", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x09a7: {Desc: "Banking Deposit Request", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x09a9: {Desc: "Banking Withdraw Request", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x09ab: {Desc: "Banking Check Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x09d0: {Desc: "Gameguard Reply", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x09d4: {Desc: "Sell Buy Complete", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x09d6: {Desc: "Buy Bulk Market", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x09d8: {Desc: "Market Close", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x09e1: {Desc: "Guild Storage Item Add", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x09e2: {Desc: "Guild Storage Item Remove", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x09e3: {Desc: "Cart To Guild Storage", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x09e4: {Desc: "Guild Storage To Cart", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x09e8: {Desc: "Rodex Open Mailbox", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x09e9: {Desc: "Rodex Close Mailbox", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x09ea: {Desc: "Rodex Read Mail", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x09ee: {Desc: "Rodex Next Maillist", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x09ef: {Desc: "Rodex Refresh Maillist", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x09f1: {Desc: "Rodex Request Zeny", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x09f3: {Desc: "Rodex Request Items", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x09f5: {Desc: "Rodex Delete Mail", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x09fb: {Desc: "Pet Evolution", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0a03: {Desc: "Rodex Cancel Write Mail", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a04: {Desc: "Rodex Add Item", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a06: {Desc: "Rodex Remove Item", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a08: {Desc: "Rodex Open Write Mail", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a13: {Desc: "Rodex Checkname", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a16: {Desc: "Dynamicnpc Create Request", Size: 26, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a19: {Desc: "Roulette Window Open", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a1b: {Desc: "Roulette Info Request", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a1d: {Desc: "Roulette Close", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a1f: {Desc: "Roulette Start", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a21: {Desc: "Roulette Claim Prize", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a25: {Desc: "Achievement Get Reward", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a2e: {Desc: "Send Change Title", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a39: {Desc: "Char Create", Size: 36, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a46: {Desc: "Stylist Change", Size: 14, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a49: {Desc: "Private Airship Request", Size: 20, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a52: {Desc: "Captcha Register", Size: 20, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a54: {Desc: "Captcha Upload Request Ack", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0a56: {Desc: "Macro Reporter Ack", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a5a: {Desc: "Macro Detector Download", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a5c: {Desc: "Macro Detector Answer", Size: 18, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a68: {Desc: "Open Ui Request", Size: 3, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a69: {Desc: "Captcha Preview Request", Size: 6, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a6c: {Desc: "Macro Reporter Select", Size: 7, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a6e: {Desc: "Rodex Send Mail", Size: -1, Type: common.INDICATED_IN_PACKET, Handler: nil, Alert: false},
    0x0a76: {Desc: "Master Login", Size: 80, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a97: {Desc: "Equip Switch Add", Size: 8, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a99: {Desc: "Equip Switch Remove", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x0a9c: {Desc: "Equip Switch Run", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0aa1: {Desc: "Refineui Select", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x0aa3: {Desc: "Refineui Refine", Size: 7, Type: common.FIXED, Handler: nil, Alert: false},
    0x0aa4: {Desc: "Refineui Close", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0aac: {Desc: "Master Login", Size: 69, Type: common.FIXED, Handler: nil, Alert: false},
    0x0ac0: {Desc: "Rodex Open Mailbox", Size: 27, Type: common.FIXED, Handler: nil, Alert: false},
    0x0ac1: {Desc: "Rodex Refresh Maillist", Size: 27, Type: common.FIXED, Handler: nil, Alert: false},
    0x0ace: {Desc: "Equip Switch Single", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x0acf: {Desc: "Master Login", Size: 68, Type: common.FIXED, Handler: nil, Alert: false},
    0x0ae8: {Desc: "Change Dress", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0aef: {Desc: "Attendance Reward Request", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0af4: {Desc: "Skill Use Location", Size: 11, Type: common.FIXED, Handler: nil, Alert: false},
    0x0b10: {Desc: "Start Skill Use", Size: 10, Type: common.FIXED, Handler: nil, Alert: false},
    0x0b11: {Desc: "Stop Skill Use", Size: 4, Type: common.FIXED, Handler: nil, Alert: false},
    0x0b14: {Desc: "Inventory Expansion Request", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0b19: {Desc: "Inventory Expansion Rejected", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0b1c: {Desc: "Ping", Size: 2, Type: common.FIXED, Handler: nil, Alert: false},
    0x0b21: {Desc: "Hotkey Change", Size: 13, Type: common.FIXED, Handler: nil, Alert: false},
    0x0baf: {Desc: "Use Packageitem", Size: 16, Type: common.FIXED, Handler: nil, Alert: false},
    0x0c23: {Desc: "Send Otp Login", Size: 9, Type: common.FIXED, Handler: nil, Alert: false},
    0x0c26: {Desc: "Master Login", Size: 94, Type: common.FIXED, Handler: nil, Alert: false},
}
